### ISSUE TITLE
Automation for layer zero rate provider factory

### ISSUE THREAD

**Issue by solarcurvey** [BalancerMaxis/multisig-ops#235]
https://github.com/witherblock/gyarados

will need to call updateRate() on each cross chain rate provider every day

**Comment by Tritium-VLK** [comment]
@solarcurvey @jubeira any idea where to get a list of all the cross chain rate providers? (onchain is better, but offhcain is ok too).

This is on mainnet, or on the chains they are on?

**Comment by Tritium-VLK** [comment]
Or is this the thing Markus already automated with OZ?

**Comment by Tritium-VLK** [comment]
more scope details from @markusbkoch 
Hey guys. Like I've said in internal chats, I think it's probably fine to start experimenting with specialized contracts like the ones witherblock has developed.

But Balancer pools require that rate providers implement IRateProvider (https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/interfaces/contracts/pool-utils/IRateProvider.sol). So I think it's safe to assume that any rate that we'll ever care about will be queriable via getRate(). Which means we can build a more generalized architecture.

For clarity and disambiguation I'll define a few terms
- OriginalRateProvider: any contract that implements IRateProvider
- Sender: a contract that interacts with the LZ endpoint to send the return of any RateProvider's getRate() on the same network to a Receiver in another network
- Receiver: a contract that receives the information from the Sender and stores it in a srcChainId => OriginalRateProviderAddress => _rate mapping
- ChildChainRateProvider: a contract that implements IRateProvider and reads the latest rate stored in Receiver for a specific srcChainId and OriginalRateProvider
- ChildChainRateProviderFactory: a contract that deploys ChildChainRateProviders (ie. create(srcChainId, OriginalRateProviderAddress)) 

Notice that the notion of mainnets and L2s is irrelevant to these definitions. We could have a OriginalRateProvider and Sender on Polygon and it's Receiver and ChildChainRateProvider on Polygon zkEVM or even Mainnet. The ChildChainRateProvider is the only contract our pools would read from, and they'd be configured to read from the relevant srcChainId/OriginalRateProviderAddress.

In addition to sending/receiving/storing the rate, I think it could be useful to also send/receive/store the srcChain timestamp at which the information was sent, so that it's easier to build monitoring systems on top of this.

What do you guys think?

**Comment by Tritium-VLK** [comment]
these rates don't change fast and we're talking about daily updates.  Would it make sense to have a configurable timelock/delay.

So for example the receiver waits timeDelaySeconds after receiving the rate before reporting it?  This would give the chance to monitor for a problematic change and try to somehow get in front of it/save the funds.  Does that make sense?
