### ISSUE TITLE
Prepair Payload for GOLD BIP

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#555]
The following this are being suggested as part of the new GOLD pools on ARbitrum

```
Reduce cap on [50GOLD/25USDC/25ETH](https://app.balancer.fi/#/base/pool/0x433f09ca08623e48bac7128b7105de678e37d988000100000000000000000047) pool to 5%
Reduce the cap on the [BADGER/rETH](https://app.balancer.fi/#/ethereum/pool/0x1ee442b5326009bb18f2f472d3e0061513d1a0ff000200000000000000000464) pool to 5%
Kill the Gauge on the current [tetuBAL stableswap poo](https://app.balancer.fi/#/polygon/pool/0xb797adfb7b268faeaa90cadbfed464c76ee599cd0002000000000000000005ba)l that is off peg with a high a-factor.
Enable a gauge with a 10% cap on the [new tetuBAL stableswap](https://app.balancer.fi/#/polygon/pool/0x7af62c1ebf97034b7542ccec13a2e79bbcf34380000000000000000000000c13) pool with an a-factor of 20.
I suggest that the 10% cap for Arbitrum AIrdrop incentives be shared between the 2 pools.
8% cap on the 50/25/25 pool
2% cap on the 25/25/25/25 pool
```

Each line here represents a change.  Everything but the caps on the bottom need something to happen onchain from a mutlisig.  In some cases gauge contracts may need to be launched first.

@Zen-Maxi normally does this work and can show you how.  Here the specs are stated again:

**Specifications:**
Enable 50/25/25 - 5% cap  (create gauge + payload to add)
Enable 25/25/25/25 - 5% cap (create gauge + payload to add)
Drop cap to 5% on 50/25/25 on base (change gauge, check perms/who can do it)
Drop cap to 5% on BADGER/rETH on mainnet (change gauge, who can do it)
Enable tetuBAL stablewap a-20 gauge with 10% CAP (create new gauge or change cap on current one + payload to add)
Kill old tetuBAL stableswap gauge (killGauge has to be called via the authorizerAdapterEntrypoint)
Configure Arbi incentive caps for 50/25/25(8%) and 25/25/25/25(2%) pools in the airdrop program config. (changes to a config file in the data_automation repo, ask shak)

**Comment by Zen-Maxi** [comment]
Howdy, we can do this in chunks. My approach is usually split things up based on the multisig we need to use. For using setRelativeWeightCap we typically grant the permission, use it, then revoke in one transaction. It is a safety practice to always revoke roles, but in some cases it is worth leaving them granted (typically emergency related or high use frequency roles). Here is the role for [setRelativeWeightCap](https://github.com/balancer/balancer-deployments/blob/8df6e330a561a2f176dc12ed619159c7ff456f87/action-ids/mainnet/action-ids.json#L726C43-L726C109), this actually covers mainnet and root gauges for all networks. Once the permission is granted, it must be executed via the AuthorizerAdapterEntrypoint for each gauge individually. For dropping the caps, the simulation can be seen here: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/9a4619b7-7c5d-4220-afb7-c1e77a82dad5

I leave out the gauge kill which is done via the DAO Multisig and AuthorizerAdaptorEntrypoint as well mainly because I think it is easier for us to drop the A factor from 500 to 20 in 10 days and to change the cap. Less delays, migration, etc than if we made a new pool, or new gauge and had to have rewards accumulate on Aura. This is up for discussion though can be done either way, will wait for Tritiums response as to why he suggests this way and refine json in the morning. Feel free to ask questions as we progress. Either way, this json will need an update for killing the gauge or changing it's weight. 

[Drop-gauge-caps-GOLD-BIP-r0.json](https://github.com/BalancerMaxis/multisig-ops/files/12902405/Drop-gauge-caps-GOLD-BIP-r0.json)

**Comment by Zen-Maxi** [comment]
Alternate route per Aura and Tritium discussions, leaving out the Tetubal portions now for a separate vote. The payload above can stand as is. Then the additional payload from the LM Multisig to add the two new gauges can be seen attached below. These are simple, permission is long standing in this case for LM Multisig to write the gaugeAdderv4 and call addGauge to add it to the GaugeController. **Always use the root gauge address here, when creating a root gauge the cap is set, and can be changed as we have done above.** 

Simulation: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/010dad49-04e4-4d27-ad1f-bc1f60cb50ad
[Enable-Arbitrum-GOLD-Gauges.json](https://github.com/BalancerMaxis/multisig-ops/files/12905727/Enable-Arbitrum-GOLD-Gauges.json)

The Balancer Maxi LM Multisig eth:0xc38c5f97B34E175FFd35407fc91a937300E33860 will interact with the GaugeAdderv4 at 0x5DbAd78818D4c8958EfF2d5b95b28385A22113Cd and call the addGauge function with the following arguments:
gauge(address): 0x72968864B06f4261b6620C69b0D179B8Ff267C0B
gaugeType(string): Arbitrum
gauge(address): 0x391adFC5895f435D12e761448b6022836F394f89
gaugeType(string): Arbitrum
