### ISSUE TITLE
Maxi Safe Signer Cleanup + swap shak for gos

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#895]
@SHAKOTN  `0x8053484489b110181a6DBA0b59Dda887e433F470` is still a signer on many safes, but needs to be rotated out.
@solarcurvey  ` 0x512fce9B07Ce64590849115EE6B32fd40eC0f5F3` left a while ago and should no longer be a signer on anything but the emergency DAO.
@0xDanko  `0x200550cAD164E8e0Cb544A9c7Dc5c833122C1438` is moving to another SP.  It is unclear if he should remain a signer on the MaxiOps safes or not.  **Need to decide this**

As per [BIP-568](https://forum.balancer.fi/t/bip-568-fund-balancer-maxis-for-q2-2024/5625), Gosuto `0x11761c7b08287d9489CD84C04DF6852F5C07107b` is now fully authorized to be a member of the maxi signer set.

The Maxi Signer set is therefore now defined as the following:
```json
{
    "zendragon": "0x7c2eA10D3e5922ba3bBBafa39Dc0677353D2AF17",
    "zekraken": "0xafFC70b81D54F229A5F50ec07e2c76D2AAAD07Ae",
    "mikeb": "0xc4591c41e01a7a654B5427f39Bbd1dEe5bD45D1D",
    "xeonus": "0x7019Be4E4eB74cA5F61224FeAf687d2b43998516",
    "tritium": "0xcf4fF1e03830D692F52EB094c52A5A6A2181Ab3F",
    "gosuto": "0x11761c7b08287d9489CD84C04DF6852F5C07107b"
}
```

Each of the below safes should be checked, and signers should be swapped out such that the signers match the list above.  Wouldn't also hurt to verify that all safes require 3 signers to exec. 

## Mainnet
- [x]  "lm": "0xc38c5f97B34E175FFd35407fc91a937300E33860",
- [x]  "fees": "0x7c68c42De679ffB0f16216154C996C354cF1161B",
- [x]  "feeManager": "0xf4A80929163C5179Ca042E1B292F5EFBBE3D89e6",
- [x]  "maxi_ops": "0x166f54F44F271407f24AA1BE415a730035637325",
- [ ]  "linearPoolController": "0x75a52c0e32397A3FC0c052E2CeB3479802713Cf4",
- [x]    "vote_incentive_recycling": "0x9ff471F9f98F42E5151C7855fD1b5aa906b1AF7e" **Already proper set on multiple chains,excluding future instances**

##  Polygon
- [x]     "lm": "0xc38c5f97B34E175FFd35407fc91a937300E33860",
 - [x]   "fees": "0x7c68c42De679ffB0f16216154C996C354cF1161B",
  
## Arbitrum
- [x]     "lm": "0xc38c5f97B34E175FFd35407fc91a937300E33860",
- [x]     "fees": "0x7c68c42De679ffB0f16216154C996C354cF1161B",
- [x]     "maxi_ops": "0x5891b90CE909d4c3540d640d2BdAAF3fD5157EAD",

## Optimism
- [x]     "lm & fees": "0x09Df1626110803C7b3b07085Ef1E053494155089",
 
## zkEVM
- [x]     "lm & fees": "0xB59Ab49CA8d064E645Bf2c546d9FE6d1d4147a09",
 
## Avalanche
 - [x]    "lm and fees": "0x326A7778DB9B741Cb2acA0DE07b9402C7685dAc6",

## Gnosis
- [x]     "lm and fees": "0x14969B55a675d13a1700F71A37511bc22D90155a",
 
## Base: 
- [x]     "lm and fees": "0x65226673F3D202E0f897C862590d7e1A992B2048",

**Comment by Zen-Maxi** [comment]
Mainnet:
- "feeManager": "0xf4A80929163C5179Ca042E1B292F5EFBBE3D89e6", is 2/7 and also has a questionable signer on it: eth:0x6bB4720473d4D7133f944785e5EE1A650C07f34e can remove if we decide. 
- "maxi_ops": "0x166f54F44F271407f24AA1BE415a730035637325", has Danko still, want to remove? 
- "linearPoolController": "0x75a52c0e32397A3FC0c052E2CeB3479802713Cf4", I am not on this safe, but maybe we sunset it since Linear pools are obsolete for the time being? I imagine lm should be used for future since pool parameter controls since it does A and swap fees now. 

Arbitrum:
-  "maxi_ops": "0x5891b90CE909d4c3540d640d2BdAAF3fD5157EAD", Danko still on can remove

Optimism:
 "lm & fees": "0x09Df1626110803C7b3b07085Ef1E053494155089"

Will edit comment once rest of networks are done.

**Comment by Zen-Maxi** [comment]
Closed out the above, danko and 0x6bB4720473d4D7133f944785e5EE1A650C07f34e removed from respective multisigs.

**Comment by Zen-Maxi** [comment]
@Tritium-VLK can you make changes to the the linear pool controller if needed? Otherwise i do not think we need it in the future just did not want to close without alignment on that.
